# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simonbs.dk" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Simon Støvring
  avatar: avatar.jpg
  gravatar: # email md5 hash
  description: "I'm Simon Støvring. I build things at Robocat." # used by search engines

  # Header and footer text
  header_text: >
    I'm Simon Støvring. I build things.
  # footer_text: <a href="/archive/">Archive</a>
  # Icons
  rss: false
  email_address: "mail@simonbs.dk" # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "simonbs"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "simonbs"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: "UA-60476988-1" # tracking id, e.g. "UA-000000-01"
  disqus_shortname:
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "page/num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed